"""
Property-based tests for SystemPromptBuilder.

Feature: trading-copilot-agent
Tests correctness properties for:
- Property 17: System prompt includes all pipeline stages
- Property 18: System prompt includes all registered tools
- Property 20: Trade context injection into system prompt

**Validates: Requirements 10.1, 10.2, 11.2**
"""

from __future__ import annotations

import pytest
from hypothesis import given, settings, strategies as st

from quantgambit.copilot.models import ToolDefinition, TradeContext
from quantgambit.copilot.prompt import SystemPromptBuilder
from quantgambit.copilot.tools.registry import ToolRegistry


# =============================================================================
# Constants
# =============================================================================

PIPELINE_STAGES = [
    "data_readiness",
    "amt_calculator",
    "global_gate",
    "profile_routing",
    "signal_check",
    "arbitration",
    "confirmation",
    "ev_gate",
    "execution_feasibility",
    "execution",
    "position_evaluation",
    "risk_check",
    "prediction_gate",
    "snapshot_builder",
    "candidate_generation",
    "candidate_veto",
    "confidence_gate",
    "confidence_position_sizer",
    "cooldown",
    "cost_data_quality",
    "ev_position_sizer",
    "fee_aware_entry",
    "minimum_hold_time",
    "session_filter",
    "session_risk",
    "strategy_trend_alignment",
    "symbol_characteristics",
]


# =============================================================================
# Strategies (Generators)
# =============================================================================

# Non-empty printable strings for tool names and descriptions.
# We use a restricted alphabet to avoid control characters that would never
# appear in real tool names/descriptions, while still exercising variety.
_tool_name_text = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N"), whitelist_characters="_-"),
    min_size=1,
    max_size=40,
).filter(lambda s: s.strip())

_tool_desc_text = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "Z", "P")),
    min_size=1,
    max_size=100,
).filter(lambda s: s.strip())


async def _noop_handler(**kwargs):
    return {}


@st.composite
def tool_definition_strategy(draw):
    """Generate a ToolDefinition with random name and description."""
    name = draw(_tool_name_text)
    description = draw(_tool_desc_text)
    return ToolDefinition(
        name=name,
        description=description,
        parameters_schema={"type": "object", "properties": {}},
        handler=_noop_handler,
    )


@st.composite
def tool_registry_strategy(draw):
    """Generate a ToolRegistry populated with 0-10 random tools."""
    tools = draw(
        st.lists(tool_definition_strategy(), min_size=0, max_size=10, unique_by=lambda t: t.name)
    )
    registry = ToolRegistry()
    for tool in tools:
        registry.register(tool)
    return registry, tools


# Strategy for non-empty identifier-like strings (trade IDs, symbols, etc.)
_identifier_text = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N"), whitelist_characters="-_"),
    min_size=1,
    max_size=30,
).filter(lambda s: s.strip())

_side_strategy = st.sampled_from(["BUY", "SELL", "buy", "sell", "Buy", "Sell"])

_price_strategy = st.floats(
    min_value=0.0001, max_value=1_000_000.0, allow_nan=False, allow_infinity=False
)

_pnl_strategy = st.floats(
    min_value=-1_000_000.0, max_value=1_000_000.0, allow_nan=False, allow_infinity=False
)

_hold_time_strategy = st.floats(
    min_value=0.0, max_value=1_000_000.0, allow_nan=False, allow_infinity=False
)


@st.composite
def trade_context_strategy(draw):
    """Generate an arbitrary TradeContext with random field values."""
    return TradeContext(
        trade_id=draw(_identifier_text),
        symbol=draw(_identifier_text),
        side=draw(_side_strategy),
        entry_price=draw(_price_strategy),
        exit_price=draw(_price_strategy),
        pnl=draw(_pnl_strategy),
        hold_time_seconds=draw(_hold_time_strategy),
        decision_trace_id=draw(st.one_of(st.none(), _identifier_text)),
    )


# =============================================================================
# Property 17: System prompt includes all pipeline stages
# =============================================================================


class TestProperty17PipelineStages:
    """
    Feature: copilot-deep-knowledge, Property 17: System prompt includes all pipeline stages

    For any system prompt generated by SystemPromptBuilder, the prompt text
    SHALL contain references to all pipeline stages from CANONICAL_STAGE_ORDER
    plus all stage files in the stages directory.

    **Validates: Requirements 1.1**
    """

    @given(data=tool_registry_strategy())
    @settings(max_examples=100)
    def test_all_pipeline_stages_present(self, data):
        """Regardless of which tools are registered, all pipeline stages appear."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build()

        for stage in PIPELINE_STAGES:
            assert stage in prompt, (
                f"Pipeline stage '{stage}' missing from system prompt"
            )

    @given(data=tool_registry_strategy(), ctx=trade_context_strategy())
    @settings(max_examples=100)
    def test_all_pipeline_stages_present_with_trade_context(self, data, ctx):
        """Pipeline stages remain present even when trade context is injected."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build(trade_context=ctx)

        for stage in PIPELINE_STAGES:
            assert stage in prompt, (
                f"Pipeline stage '{stage}' missing from system prompt with trade context"
            )


# =============================================================================
# Property 18: System prompt includes all registered tools
# =============================================================================


class TestProperty18RegisteredTools:
    """
    Feature: trading-copilot-agent, Property 18: System prompt includes all registered tools

    For any set of tools registered in the ToolRegistry, the system prompt
    generated by SystemPromptBuilder SHALL contain the name and description
    of each registered tool.

    **Validates: Requirements 10.2**
    """

    @given(data=tool_registry_strategy())
    @settings(max_examples=100)
    def test_all_tool_names_and_descriptions_present(self, data):
        """Every registered tool's name and description appear in the prompt."""
        registry, tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build()

        for tool in tools:
            assert tool.name in prompt, (
                f"Tool name '{tool.name}' missing from system prompt"
            )
            assert tool.description in prompt, (
                f"Tool description '{tool.description}' missing from system prompt"
            )

    @given(data=tool_registry_strategy(), ctx=trade_context_strategy())
    @settings(max_examples=100)
    def test_all_tool_names_and_descriptions_present_with_trade_context(self, data, ctx):
        """Tool names and descriptions remain present when trade context is injected."""
        registry, tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build(trade_context=ctx)

        for tool in tools:
            assert tool.name in prompt, (
                f"Tool name '{tool.name}' missing from system prompt with trade context"
            )
            assert tool.description in prompt, (
                f"Tool description '{tool.description}' missing from system prompt with trade context"
            )


# =============================================================================
# Property 20: Trade context injection into system prompt
# =============================================================================


class TestProperty20TradeContextInjection:
    """
    Feature: trading-copilot-agent, Property 20: Trade context injection into system prompt

    For any TradeContext object, the system prompt generated by
    SystemPromptBuilder with that trade context SHALL contain the trade ID,
    symbol, side, entry price, exit price, PnL, and hold time values from
    the TradeContext.

    **Validates: Requirements 11.2**
    """

    @given(ctx=trade_context_strategy())
    @settings(max_examples=100)
    def test_trade_context_fields_present_in_prompt(self, ctx):
        """All TradeContext field values appear in the generated prompt."""
        registry = ToolRegistry()
        builder = SystemPromptBuilder(registry)
        prompt = builder.build(trade_context=ctx)

        assert ctx.trade_id in prompt, (
            f"trade_id '{ctx.trade_id}' missing from prompt"
        )
        assert ctx.symbol in prompt, (
            f"symbol '{ctx.symbol}' missing from prompt"
        )
        assert ctx.side in prompt, (
            f"side '{ctx.side}' missing from prompt"
        )
        assert str(ctx.entry_price) in prompt, (
            f"entry_price '{ctx.entry_price}' missing from prompt"
        )
        assert str(ctx.exit_price) in prompt, (
            f"exit_price '{ctx.exit_price}' missing from prompt"
        )
        assert str(ctx.pnl) in prompt, (
            f"pnl '{ctx.pnl}' missing from prompt"
        )
        assert str(ctx.hold_time_seconds) in prompt, (
            f"hold_time_seconds '{ctx.hold_time_seconds}' missing from prompt"
        )

    @given(data=tool_registry_strategy(), ctx=trade_context_strategy())
    @settings(max_examples=100)
    def test_trade_context_fields_present_with_tools(self, data, ctx):
        """Trade context fields are present even when tools are registered."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build(trade_context=ctx)

        assert ctx.trade_id in prompt
        assert ctx.symbol in prompt
        assert ctx.side in prompt
        assert str(ctx.entry_price) in prompt
        assert str(ctx.exit_price) in prompt
        assert str(ctx.pnl) in prompt
        assert str(ctx.hold_time_seconds) in prompt


# =============================================================================
# Feature: copilot-deep-knowledge
# Property 1: System prompt contains all pipeline stage names
# =============================================================================


# All stage names: canonical order + flexible-position + additional stages
ALL_PIPELINE_STAGE_NAMES = [
    # Canonical order stages
    "data_readiness",
    "amt_calculator",
    "global_gate",
    "profile_routing",
    "signal_check",
    "arbitration",
    "confirmation",
    "ev_gate",
    "execution_feasibility",
    "execution",
    # Flexible-position stages
    "position_evaluation",
    "risk_check",
    "prediction_gate",
    # Additional stages from stages directory
    "snapshot_builder",
    "candidate_generation",
    "candidate_veto",
    "confidence_gate",
    "confidence_position_sizer",
    "cooldown",
    "cost_data_quality",
    "ev_position_sizer",
    "fee_aware_entry",
    "minimum_hold_time",
    "session_filter",
    "session_risk",
    "strategy_trend_alignment",
    "symbol_characteristics",
]


class TestProperty1SystemPromptContainsAllStageNames:
    """
    Feature: copilot-deep-knowledge, Property 1: System prompt contains all pipeline stage names

    For any pipeline stage name in the canonical stage order plus all stage
    files in the stages directory, the built system prompt string SHALL
    contain that stage name.

    **Validates: Requirements 1.1**
    """

    @given(data=tool_registry_strategy())
    @settings(max_examples=100)
    def test_all_stage_names_present_in_prompt(self, data):
        """For any random tool registry, every pipeline stage name appears in the prompt."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build()

        for stage_name in ALL_PIPELINE_STAGE_NAMES:
            assert stage_name in prompt, (
                f"Pipeline stage '{stage_name}' missing from system prompt"
            )

    @given(data=tool_registry_strategy(), ctx=trade_context_strategy())
    @settings(max_examples=100)
    def test_all_stage_names_present_with_trade_context(self, data, ctx):
        """Stage names remain present even when trade context is injected."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build(trade_context=ctx)

        for stage_name in ALL_PIPELINE_STAGE_NAMES:
            assert stage_name in prompt, (
                f"Pipeline stage '{stage_name}' missing from system prompt "
                f"when trade context is injected"
            )


# =============================================================================
# Feature: copilot-deep-knowledge
# Property 2: System prompt preserves canonical stage ordering
# =============================================================================

# The canonical order as defined by get_canonical_stage_order()
CANONICAL_STAGE_ORDER = [
    "data_readiness",
    "amt_calculator",
    "global_gate",
    "profile_routing",
    "signal_check",
    "arbitration",
    "confirmation",
    "ev_gate",
    "execution_feasibility",
    "execution",
]


def _find_stage_heading(prompt: str, stage_name: str) -> int:
    """Find the position of a stage's heading entry in the prompt.

    Stages are formatted as ``**stage_name (`` in the prompt (e.g.
    ``**data_readiness (DataReadinessStage)**``).  We search for the
    heading marker to avoid false positives from incidental mentions of
    the stage name in other descriptions.
    """
    marker = f"**{stage_name} ("
    pos = prompt.find(marker)
    if pos != -1:
        return pos
    # Fallback: try bold marker without parenthetical class name
    marker_alt = f"**{stage_name}"
    return prompt.find(marker_alt)


class TestProperty2SystemPromptPreservesCanonicalOrdering:
    """
    Feature: copilot-deep-knowledge, Property 2: System prompt preserves canonical stage ordering

    For any pair of stages (A, B) where A precedes B in the canonical stage
    order, the first occurrence of A's name in the system prompt SHALL appear
    before the first occurrence of B's name. We locate each stage by its
    heading entry (``**stage_name (``) to avoid false positives from
    incidental mentions in other stage descriptions.

    **Validates: Requirements 1.2**
    """

    @given(data=tool_registry_strategy())
    @settings(max_examples=100)
    def test_canonical_ordering_preserved(self, data):
        """For any random tool registry, canonical stage order is preserved in the prompt."""
        registry, _tools = data
        builder = SystemPromptBuilder(registry)
        prompt = builder.build()

        for i in range(len(CANONICAL_STAGE_ORDER)):
            for j in range(i + 1, len(CANONICAL_STAGE_ORDER)):
                stage_a = CANONICAL_STAGE_ORDER[i]
                stage_b = CANONICAL_STAGE_ORDER[j]
                pos_a = _find_stage_heading(prompt, stage_a)
                pos_b = _find_stage_heading(prompt, stage_b)
                assert pos_a != -1, (
                    f"Stage heading for '{stage_a}' not found in system prompt"
                )
                assert pos_b != -1, (
                    f"Stage heading for '{stage_b}' not found in system prompt"
                )
                assert pos_a < pos_b, (
                    f"Canonical ordering violated: '{stage_a}' (pos {pos_a}) "
                    f"should appear before '{stage_b}' (pos {pos_b})"
                )

    @given(
        data=tool_registry_strategy(),
        pair_idx=st.tuples(
            st.integers(min_value=0, max_value=len(CANONICAL_STAGE_ORDER) - 2),
            st.integers(min_value=1, max_value=len(CANONICAL_STAGE_ORDER) - 1),
        ).filter(lambda t: t[0] < t[1]),
    )
    @settings(max_examples=100)
    def test_random_pair_ordering_preserved(self, data, pair_idx):
        """For any random pair (A, B) where A precedes B, ordering holds."""
        registry, _tools = data
        idx_a, idx_b = pair_idx
        stage_a = CANONICAL_STAGE_ORDER[idx_a]
        stage_b = CANONICAL_STAGE_ORDER[idx_b]

        builder = SystemPromptBuilder(registry)
        prompt = builder.build()

        pos_a = _find_stage_heading(prompt, stage_a)
        pos_b = _find_stage_heading(prompt, stage_b)
        assert pos_a != -1, f"Stage heading for '{stage_a}' not found in system prompt"
        assert pos_b != -1, f"Stage heading for '{stage_b}' not found in system prompt"
        assert pos_a < pos_b, (
            f"Canonical ordering violated: '{stage_a}' (pos {pos_a}) "
            f"should appear before '{stage_b}' (pos {pos_b})"
        )
