"""
Metrics collection and reporting system
Designed for future Prometheus/Grafana integration
"""
import time
from typing import Dict, Any, List, Optional, Callable
from collections import defaultdict, deque
from datetime import datetime, timedelta
from enum import Enum
import statistics
import psutil
import asyncio

from quantgambit.deeptrader_core.observability.logger import get_logger


class MetricType(Enum):
    """Types of metrics"""
    COUNTER = "counter"      # Monotonically increasing value
    GAUGE = "gauge"         # Point-in-time value
    HISTOGRAM = "histogram" # Distribution of values
    SUMMARY = "summary"     # Quantiles over sliding time window


class Metric:
    """Individual metric definition"""

    def __init__(self, name: str, description: str, metric_type: MetricType,
                 labels: List[str] = None):
        self.name = name
        self.description = description
        self.metric_type = metric_type
        self.labels = labels or []
        self.values = defaultdict(float)
        self.timestamps = defaultdict(list)
        self.samples = defaultdict(list)  # For histograms

    def set(self, value: float, labels: Dict[str, str] = None):
        """Set gauge value"""
        label_key = self._label_key(labels)
        self.values[label_key] = value
        self.timestamps[label_key].append(time.time())

    def increment(self, amount: float = 1.0, labels: Dict[str, str] = None):
        """Increment counter value"""
        label_key = self._label_key(labels)
        self.values[label_key] += amount
        self.timestamps[label_key].append(time.time())

    def observe(self, value: float, labels: Dict[str, str] = None):
        """Observe value for histogram/summary"""
        label_key = self._label_key(labels)
        self.samples[label_key].append((time.time(), value))

        # Keep only recent samples (last 5 minutes)
        cutoff = time.time() - 300
        self.samples[label_key] = [
            (ts, val) for ts, val in self.samples[label_key] if ts > cutoff
        ]

    def get_value(self, labels: Dict[str, str] = None) -> float:
        """Get current value"""
        label_key = self._label_key(labels)
        return self.values[label_key]

    def get_stats(self, labels: Dict[str, str] = None) -> Dict[str, Any]:
        """Get statistical summary for histogram data"""
        label_key = self._label_key(labels)
        samples = [val for _, val in self.samples[label_key]]

        if not samples:
            return {"count": 0, "mean": 0, "min": 0, "max": 0, "p50": 0, "p95": 0, "p99": 0}

        return {
            "count": len(samples),
            "mean": statistics.mean(samples),
            "min": min(samples),
            "max": max(samples),
            "p50": statistics.median(samples),
            "p95": statistics.quantiles(samples, n=20)[18],  # 95th percentile
            "p99": statistics.quantiles(samples, n=100)[98] if len(samples) >= 100 else max(samples)
        }

    def _label_key(self, labels: Dict[str, str] = None) -> str:
        """Generate label key for storage"""
        if not labels:
            return "default"

        # Sort labels for consistent key generation
        sorted_labels = sorted(labels.items())
        return "|".join(f"{k}={v}" for k, v in sorted_labels)


class MetricsRegistry:
    """Registry of all metrics"""

    def __init__(self):
        self.metrics: Dict[str, Metric] = {}
        self._initialize_standard_metrics()

    def _initialize_standard_metrics(self):
        """Initialize standard trading metrics"""

        # Worker metrics
        self.create_metric(
            "worker_uptime_seconds",
            "Time worker has been running",
            MetricType.GAUGE,
            ["worker_name"]
        )

        self.create_metric(
            "worker_messages_processed_total",
            "Total messages processed by worker",
            MetricType.COUNTER,
            ["worker_name"]
        )

        self.create_metric(
            "worker_errors_total",
            "Total errors encountered by worker",
            MetricType.COUNTER,
            ["worker_name", "error_type"]
        )

        # Strategy metrics
        self.create_metric(
            "strategy_signals_generated_total",
            "Total signals generated by strategy",
            MetricType.COUNTER,
            ["strategy_id", "strategy_version"]
        )

        self.create_metric(
            "strategy_win_rate",
            "Strategy win rate (0-1)",
            MetricType.GAUGE,
            ["strategy_id", "strategy_version"]
        )

        self.create_metric(
            "strategy_avg_return_percent",
            "Average return per trade",
            MetricType.GAUGE,
            ["strategy_id", "strategy_version"]
        )

        self.create_metric(
            "strategy_sharpe_ratio",
            "Strategy Sharpe ratio",
            MetricType.GAUGE,
            ["strategy_id", "strategy_version"]
        )

        # Risk metrics
        self.create_metric(
            "risk_checks_passed_total",
            "Total risk checks that passed",
            MetricType.COUNTER,
            ["check_type"]
        )

        self.create_metric(
            "risk_checks_failed_total",
            "Total risk checks that failed",
            MetricType.COUNTER,
            ["check_type"]
        )

        self.create_metric(
            "position_exposure_percent",
            "Current position exposure as percentage of capital",
            MetricType.GAUGE,
            ["user_id"]
        )

        # Execution metrics
        self.create_metric(
            "orders_executed_total",
            "Total orders executed",
            MetricType.COUNTER,
            ["exchange", "order_type", "side"]
        )

        self.create_metric(
            "order_execution_time_seconds",
            "Time taken to execute orders",
            MetricType.HISTOGRAM,
            ["exchange"]
        )

        self.create_metric(
            "slippage_bps",
            "Order slippage in basis points",
            MetricType.HISTOGRAM,
            ["exchange", "symbol"]
        )

        # Market data metrics
        self.create_metric(
            "market_data_latency_seconds",
            "Latency of market data updates",
            MetricType.HISTOGRAM,
            ["exchange", "symbol", "data_type"]
        )

        self.create_metric(
            "websocket_connections_active",
            "Number of active WebSocket connections",
            MetricType.GAUGE,
            ["exchange"]
        )

        self.create_metric(
            "api_rate_limits_remaining",
            "Remaining API rate limit calls",
            MetricType.GAUGE,
            ["exchange", "endpoint"]
        )

        # System metrics
        self.create_metric(
            "system_cpu_usage_percent",
            "System CPU usage percentage",
            MetricType.GAUGE
        )

        self.create_metric(
            "system_memory_usage_bytes",
            "System memory usage in bytes",
            MetricType.GAUGE
        )

        self.create_metric(
            "redis_queue_depth",
            "Number of messages in Redis queue",
            MetricType.GAUGE,
            ["stream_name"]
        )

    def create_metric(self, name: str, description: str, metric_type: MetricType,
                     labels: List[str] = None) -> Metric:
        """Create a new metric"""
        if name in self.metrics:
            raise ValueError(f"Metric {name} already exists")

        metric = Metric(name, description, metric_type, labels)
        self.metrics[name] = metric
        return metric

    def get_metric(self, name: str) -> Optional[Metric]:
        """Get metric by name"""
        return self.metrics.get(name)

    def increment_counter(self, name: str, labels: Dict[str, str] = None, amount: float = 1.0):
        """Increment a counter metric"""
        metric = self.get_metric(name)
        if metric and metric.metric_type == MetricType.COUNTER:
            metric.increment(amount, labels)

    def set_gauge(self, name: str, value: float, labels: Dict[str, str] = None):
        """Set a gauge metric"""
        metric = self.get_metric(name)
        if metric and metric.metric_type == MetricType.GAUGE:
            metric.set(value, labels)

    def observe_histogram(self, name: str, value: float, labels: Dict[str, str] = None):
        """Observe a value for histogram metric"""
        metric = self.get_metric(name)
        if metric and metric.metric_type in [MetricType.HISTOGRAM, MetricType.SUMMARY]:
            metric.observe(value, labels)

    def collect_system_metrics(self):
        """Collect system-level metrics"""
        try:
            # CPU usage
            cpu_percent = psutil.cpu_percent(interval=1)
            self.set_gauge("system_cpu_usage_percent", cpu_percent)

            # Memory usage
            memory = psutil.virtual_memory()
            self.set_gauge("system_memory_usage_bytes", memory.used)

        except Exception as e:
            get_logger("metrics").error("Failed to collect system metrics", error=str(e))

    def get_all_metrics(self) -> Dict[str, Any]:
        """Get all metrics data for reporting"""
        result = {}

        for name, metric in self.metrics.items():
            result[name] = {
                "description": metric.description,
                "type": metric.metric_type.value,
                "values": dict(metric.values),
                "stats": metric.get_stats() if metric.metric_type in [MetricType.HISTOGRAM, MetricType.SUMMARY] else None
            }

        return result

    def export_prometheus_format(self) -> str:
        """Export metrics in Prometheus format"""
        lines = []

        for name, metric in self.metrics.items():
            lines.append(f"# HELP {name} {metric.description}")
            lines.append(f"# TYPE {name} {metric.metric_type.value}")

            for label_key, value in metric.values.items():
                if label_key == "default":
                    lines.append(f"{name} {value}")
                else:
                    # Parse labels back from key
                    labels = {}
                    for label_pair in label_key.split("|"):
                        if "=" in label_pair:
                            k, v = label_pair.split("=", 1)
                            labels[k] = v

                    label_str = ",".join(f'{k}="{v}"' for k, v in labels.items())
                    lines.append(f'{name}{{{label_str}}} {value}')

        return "\n".join(lines) + "\n"


# Global metrics registry
metrics_registry = MetricsRegistry()


class MetricsCollector:
    """Automated metrics collection"""

    def __init__(self):
        self.is_running = False
        self.collection_interval = 30  # seconds

    async def start_collection(self):
        """Start periodic metrics collection"""
        self.is_running = True

        while self.is_running:
            try:
                metrics_registry.collect_system_metrics()

                # Could add more automated collection here
                # - Queue depths
                # - Worker health
                # - Database connections
                # - External API health

                await asyncio.sleep(self.collection_interval)

            except Exception as e:
                get_logger("metrics").error("Metrics collection failed", error=str(e))
                await asyncio.sleep(self.collection_interval)

    def stop_collection(self):
        """Stop metrics collection"""
        self.is_running = False


# Convenience functions for common metrics updates
def increment_worker_messages(worker_name: str):
    """Increment worker message counter"""
    metrics_registry.increment_counter(
        "worker_messages_processed_total",
        {"worker_name": worker_name}
    )

def record_worker_error(worker_name: str, error_type: str = "unknown"):
    """Record worker error"""
    metrics_registry.increment_counter(
        "worker_errors_total",
        {"worker_name": worker_name, "error_type": error_type}
    )

def record_strategy_signal(strategy_id: str, strategy_version: str = "1.0.0"):
    """Record strategy signal generation"""
    metrics_registry.increment_counter(
        "strategy_signals_generated_total",
        {"strategy_id": strategy_id, "strategy_version": strategy_version}
    )

def update_strategy_performance(strategy_id: str, win_rate: float, avg_return: float,
                              sharpe_ratio: float, strategy_version: str = "1.0.0"):
    """Update strategy performance metrics"""
    metrics_registry.set_gauge(
        "strategy_win_rate",
        win_rate,
        {"strategy_id": strategy_id, "strategy_version": strategy_version}
    )
    metrics_registry.set_gauge(
        "strategy_avg_return_percent",
        avg_return,
        {"strategy_id": strategy_id, "strategy_version": strategy_version}
    )
    metrics_registry.set_gauge(
        "strategy_sharpe_ratio",
        sharpe_ratio,
        {"strategy_id": strategy_id, "strategy_version": strategy_version}
    )

def record_order_execution(exchange: str, order_type: str, side: str):
    """Record successful order execution"""
    metrics_registry.increment_counter(
        "orders_executed_total",
        {"exchange": exchange, "order_type": order_type, "side": side}
    )

def record_execution_time(exchange: str, execution_time_seconds: float):
    """Record order execution time"""
    metrics_registry.observe_histogram(
        "order_execution_time_seconds",
        execution_time_seconds,
        {"exchange": exchange}
    )

def record_slippage(symbol: str, exchange: str, slippage_bps: float):
    """Record order slippage"""
    metrics_registry.observe_histogram(
        "slippage_bps",
        slippage_bps,
        {"exchange": exchange, "symbol": symbol}
    )

def update_websocket_connections(exchange: str, count: int):
    """Update active WebSocket connection count"""
    metrics_registry.set_gauge(
        "websocket_connections_active",
        count,
        {"exchange": exchange}
    )

def update_queue_depth(stream_name: str, depth: int):
    """Update Redis queue depth"""
    metrics_registry.set_gauge(
        "redis_queue_depth",
        depth,
        {"stream_name": stream_name}
    )
