"""
Base strategy class for trading strategies
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
from datetime import datetime
from config.strategies import TradingMode, StrategyConfig
from quantgambit.deeptrader_core.storage.postgres_models import UserTradingSettings


class TradingSignal:
    """Represents a trading signal generated by a strategy"""

    def __init__(
        self,
        strategy_id: str,
        symbol: str,
        exchange: str,
        action: str,  # 'buy', 'sell', 'hold'
        confidence: float,  # 0-10 scale
        reasoning: str,
        features_snapshot: Dict[str, Any],
        user_id: str,
        position_size_usd: float = None,
        stop_loss_price: float = None,
        take_profit_price: float = None,
        entry_price: float = None,
        risk_reward_ratio: float = None,
        holding_period_minutes: int = None
    ):
        self.strategy_id = strategy_id
        self.symbol = symbol
        self.exchange = exchange
        self.action = action
        self.confidence = confidence
        self.reasoning = reasoning
        self.features_snapshot = features_snapshot
        self.user_id = user_id
        self.position_size_usd = position_size_usd
        self.stop_loss_price = stop_loss_price
        self.take_profit_price = take_profit_price
        self.entry_price = entry_price
        self.risk_reward_ratio = risk_reward_ratio
        self.holding_period_minutes = holding_period_minutes
        self.timestamp = datetime.utcnow()
        self.signal_id = f"{strategy_id}_{symbol}_{exchange}_{int(self.timestamp.timestamp())}"

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for serialization"""
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "exchange": self.exchange,
            "action": self.action,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "features_snapshot": self.features_snapshot,
            "user_id": self.user_id,
            "position_size_usd": self.position_size_usd,
            "stop_loss_price": self.stop_loss_price,
            "take_profit_price": self.take_profit_price,
            "entry_price": self.entry_price,
            "risk_reward_ratio": self.risk_reward_ratio,
            "holding_period_minutes": self.holding_period_minutes,
            "timestamp": self.timestamp.isoformat()
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'TradingSignal':
        """Create signal from dictionary"""
        signal = cls(
            strategy_id=data["strategy_id"],
            symbol=data["symbol"],
            exchange=data["exchange"],
            action=data["action"],
            confidence=data["confidence"],
            reasoning=data["reasoning"],
            features_snapshot=data["features_snapshot"],
            user_id=data["user_id"],
            position_size_usd=data.get("position_size_usd"),
            stop_loss_price=data.get("stop_loss_price"),
            take_profit_price=data.get("take_profit_price"),
            entry_price=data.get("entry_price"),
            risk_reward_ratio=data.get("risk_reward_ratio"),
            holding_period_minutes=data.get("holding_period_minutes")
        )
        signal.timestamp = datetime.fromisoformat(data["timestamp"])
        signal.signal_id = data["signal_id"]
        return signal


class BaseStrategy(ABC):
    """Abstract base class for trading strategies"""

    def __init__(self, strategy_config: StrategyConfig):
        self.config = strategy_config
        self.name = strategy_config.name
        self.strategy_id = strategy_config.name.lower().replace(" ", "_")
        self.trading_mode = strategy_config.trading_mode

        # Performance tracking
        self.signals_generated = 0
        self.last_signal_time = None
        self.consecutive_losses = 0

    @abstractmethod
    async def analyze_market(self, features: Dict[str, Any], user_settings: Dict[str, Any]) -> Optional[TradingSignal]:
        """
        Analyze market features and generate trading signals

        Args:
            features: Comprehensive feature dictionary
            user_settings: User's trading settings from database

        Returns:
            TradingSignal if conditions are met, None otherwise
        """
        pass

    def should_generate_signal(self, features: Dict[str, Any], user_settings: Dict[str, Any]) -> bool:
        """Check if conditions are right to generate a signal"""
        # Check minimum feature confidence
        feature_confidence = features.get("feature_confidence", 0)
        if feature_confidence < 0.5:  # Require at least 50% confidence in features
            return False

        # Check data quality
        data_quality = features.get("data_quality", {})
        if data_quality.get("overall_quality") in ["poor", "unknown"]:
            return False

        # Check user settings compliance
        if not self._validate_user_settings(user_settings):
            return False

        # Check trading hours (if applicable)
        if not self._validate_trading_hours(user_settings):
            return False

        # Check consecutive losses limit
        if self.consecutive_losses >= 5:  # Strategy-specific circuit breaker
            return False

        # Check minimum time between signals
        if self.last_signal_time:
            time_since_last = (datetime.utcnow() - self.last_signal_time).total_seconds()
            min_interval = self._get_minimum_signal_interval(user_settings)
            if time_since_last < min_interval:
                return False

        return True

    def _validate_user_settings(self, user_settings: Dict[str, Any]) -> bool:
        """Validate that user settings allow this strategy"""
        # Check if strategy is enabled
        enabled_tokens = user_settings.get("enabled_tokens", [])
        if self.config.symbol not in enabled_tokens:
            return False

        # Check confidence threshold
        min_confidence = user_settings.get("ai_confidence_threshold", 7.0)
        if self.config.confidence_threshold < min_confidence:
            return False

        # Check trading mode compatibility
        if self.trading_mode == TradingMode.SCALPING:
            if not user_settings.get("scalping_mode", False):
                return False
        elif self.trading_mode == TradingMode.DAY_TRADING:
            if not user_settings.get("day_trading_enabled", False):
                return False

        return True

    def _validate_trading_hours(self, user_settings: Dict[str, Any]) -> bool:
        """Validate current time is within allowed trading hours"""
        current_time = datetime.utcnow()

        # Check day trading hours
        if self.trading_mode == TradingMode.DAY_TRADING and user_settings.get("day_trading_enabled"):
            start_time = user_settings.get("day_trading_start_time", "09:30:00")
            end_time = user_settings.get("day_trading_end_time", "15:30:00")
            days_only = user_settings.get("day_trading_days_only", False)

            # Parse times
            start_hour, start_min, _ = map(int, start_time.split(":"))
            end_hour, end_min, _ = map(int, end_time.split(":"))

            start_minutes = start_hour * 60 + start_min
            end_minutes = end_hour * 60 + end_min
            current_minutes = current_time.hour * 60 + current_time.minute

            # Check day of week (Monday = 0, Sunday = 6)
            if days_only and current_time.weekday() >= 5:  # Saturday/Sunday
                return False

            # Check time window
            if end_minutes < start_minutes:  # Overnight window
                if not (current_minutes >= start_minutes or current_minutes <= end_minutes):
                    return False
            else:  # Same day window
                if not (start_minutes <= current_minutes <= end_minutes):
                    return False

        return True

    def _get_minimum_signal_interval(self, user_settings: Dict[str, Any]) -> int:
        """Get minimum seconds between signals based on strategy type"""
        if self.trading_mode == TradingMode.SCALPING:
            return user_settings.get("scalping_min_volume_multiplier", 2) * 60  # 2-5 minutes
        elif self.trading_mode == TradingMode.DAY_TRADING:
            return 300  # 5 minutes
        else:
            return 900  # 15 minutes for swing trading

    def calculate_position_size(self, features: Dict[str, Any], user_settings: Dict[str, Any],
                              current_price: float, available_capital: float) -> float:
        """Calculate position size based on risk management"""
        # Base position size from user settings
        max_position_percent = user_settings.get("max_position_size_percent", 0.10)
        base_size = available_capital * max_position_percent

        # Adjust based on strategy confidence
        confidence_multiplier = min(self.config.confidence_threshold / 10.0, 1.0)
        base_size *= confidence_multiplier

        # Adjust based on volatility (higher volatility = smaller position)
        volatility = features.get("realized_volatility", 0.01)
        volatility_adjustment = max(0.5, 1.0 - (volatility * 10))  # Reduce size in high vol
        base_size *= volatility_adjustment

        # Adjust based on market regime
        regime = features.get("market_regime", "")
        if "strong_trend" in regime:
            base_size *= 1.2  # Increase in strong trends
        elif "ranging" in regime:
            base_size *= 0.8  # Decrease in ranging markets

        # Convert to USD value
        position_usd = min(base_size, available_capital * 0.1)  # Max 10% of capital

        return position_usd

    def calculate_stop_loss(self, entry_price: float, features: Dict[str, Any],
                          user_settings: Dict[str, Any], is_long: bool) -> float:
        """Calculate stop loss price"""
        # Get base stop loss percentage
        if self.trading_mode == TradingMode.SCALPING:
            base_stop_percent = user_settings.get("scalping_stop_loss_percent", 0.002)
        elif self.trading_mode == TradingMode.DAY_TRADING:
            base_stop_percent = user_settings.get("day_trading_stop_loss_percent", 0.005)
        else:
            base_stop_percent = user_settings.get("swing_stop_loss_percent", 0.02)

        # Adjust based on volatility
        volatility = features.get("realized_volatility", 0.01)
        volatility_adjustment = 1 + (volatility * 5)  # Increase stop in high volatility
        stop_percent = base_stop_percent * volatility_adjustment

        # Calculate price
        if is_long:
            stop_price = entry_price * (1 - stop_percent)
        else:
            stop_price = entry_price * (1 + stop_percent)

        return stop_price

    def calculate_take_profit(self, entry_price: float, stop_price: float,
                            features: Dict[str, Any], user_settings: Dict[str, Any],
                            is_long: bool) -> float:
        """Calculate take profit price"""
        # Base risk-reward ratio
        if self.trading_mode == TradingMode.SCALPING:
            rr_ratio = 1.5  # 1:1.5 for scalping
        elif self.trading_mode == TradingMode.DAY_TRADING:
            rr_ratio = 2.0  # 1:2 for day trading
        else:
            rr_ratio = 3.0  # 1:3 for swing trading

        # Calculate risk amount
        risk_amount = abs(entry_price - stop_price)

        # Calculate reward amount
        reward_amount = risk_amount * rr_ratio

        # Calculate take profit price
        if is_long:
            take_profit = entry_price + reward_amount
        else:
            take_profit = entry_price - reward_amount

        return take_profit

    def update_performance(self, signal: TradingSignal, outcome: str):
        """Update strategy performance metrics"""
        self.signals_generated += 1
        self.last_signal_time = datetime.utcnow()

        if outcome == "loss":
            self.consecutive_losses += 1
        elif outcome == "win":
            self.consecutive_losses = 0

    def get_performance_metrics(self) -> Dict[str, Any]:
        """Get strategy performance metrics"""
        return {
            "strategy_id": self.strategy_id,
            "signals_generated": self.signals_generated,
            "consecutive_losses": self.consecutive_losses,
            "last_signal_time": self.last_signal_time.isoformat() if self.last_signal_time else None,
            "is_active": self.consecutive_losses < 5  # Deactivate after 5 consecutive losses
        }

    def reset_performance(self):
        """Reset performance metrics"""
        self.signals_generated = 0
        self.last_signal_time = None
        self.consecutive_losses = 0
