"""
Core Types - Shared dataclasses for the profile system

Defines the key data structures for profile-based strategy routing:
- Features: Market state snapshot for decision making
- AccountState: Risk and position state
- Profile: Market regime classification
- StrategySignal: Strategy output for execution
- MarketSnapshot: Frozen snapshot for pre-trade gating
- TradeCandidate: Proposed trade with expected edge
- GateDecision: Structured gate pass/fail result
- ExitType/ExitDecision: Exit classification (safety vs invalidation)
- SymbolCharacteristics: Rolling statistics for symbol-adaptive parameters
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict, Any, Set
import time
import warnings
import logging

# Module-level logger for deprecation warnings
_logger = logging.getLogger(__name__)

# Track which deprecation warnings have been logged (once per session)
_deprecation_warnings_logged: Set[str] = set()


def _log_deprecation_warning(old_name: str, new_name: str) -> None:
    """
    Log a deprecation warning once per session for a renamed field.
    
    This helper ensures that deprecation warnings are only logged once per
    field name per session to avoid log spam.
    
    Args:
        old_name: The deprecated field name
        new_name: The new field name to use instead
    """
    if old_name not in _deprecation_warnings_logged:
        _deprecation_warnings_logged.add(old_name)
        msg = f"MarketSnapshot.{old_name} is deprecated, use {new_name} instead"
        _logger.warning(msg)
        warnings.warn(msg, DeprecationWarning, stacklevel=3)


@dataclass
class Features:
    """Market features snapshot for profile classification and strategy execution"""
    symbol: str
    price: float
    spread: float
    rotation_factor: float
    position_in_value: str  # "below", "inside", "above"
    
    # Optional fields with defaults
    timestamp: float = 0.0
    
    # AMT distances (can be calculated from absolute levels)
    distance_to_val: float = 0.0
    distance_to_vah: float = 0.0
    distance_to_poc: float = 0.0
    
    # BPS versions of AMT distances (canonical units)
    distance_to_poc_bps: Optional[float] = None
    distance_to_vah_bps: Optional[float] = None
    distance_to_val_bps: Optional[float] = None
    
    # AMT absolute levels (for strategies that need them)
    value_area_low: Optional[float] = None
    value_area_high: Optional[float] = None
    point_of_control: Optional[float] = None
    
    # HTF indicators
    ema_fast_15m: float = 0.0
    ema_slow_15m: float = 0.0
    atr_5m: float = 0.0
    atr_5m_baseline: float = 0.0
    vwap: float = 0.0
    
    # Trend indicators (for pipeline unification)
    trend_direction: str = "flat"  # "up", "down", "flat"
    trend_strength: float = 0.0  # 0.0 to 1.0
    
    # Microstructure
    trades_per_second: float = 0.0
    orderbook_imbalance: float = 0.0
    orderflow_imbalance: Optional[float] = None
    bid_depth_usd: float = 0.0
    ask_depth_usd: float = 0.0


@dataclass
class AccountState:
    """Account and risk state for position sizing and limits"""
    equity: float
    daily_pnl: float
    max_daily_loss: float
    open_positions: int
    symbol_open_positions: int
    symbol_daily_pnl: float


@dataclass
class Profile:
    """Market regime classification
    
    Session Risk Fields (Requirements 5.1, 5.2, 5.3):
    - position_size_multiplier: Scaling factor for position sizes (0.0-1.25)
    - preferred_strategies: List of strategy IDs preferred for this session
    - session_risk_reason: Human-readable reason for session risk adjustment
    """
    id: str
    trend: str          # "up", "down", "flat"
    volatility: str     # "low", "normal", "high"
    value_location: str # "below", "inside", "above"
    session: str        # "asia", "europe", "us", "overnight"
    risk_mode: str      # "off", "conservative", "normal"
    
    # Session risk fields (Requirements 5.1, 5.2, 5.3)
    position_size_multiplier: float = 1.0
    preferred_strategies: Optional[List[str]] = None
    session_risk_reason: Optional[str] = None


@dataclass
class StrategySignal:
    """Trading signal generated by a strategy"""
    strategy_id: str
    symbol: str
    side: str  # "long" / "short"
    size: float
    entry_price: float
    stop_loss: float
    take_profit: float
    meta_reason: str
    profile_id: str  # Track which profile generated this
    # Time budget parameters (MFT scalping) - populated from profile risk params
    expected_horizon_sec: Optional[float] = None  # How long signal is expected to be valid
    time_to_work_sec: Optional[float] = None  # T_work: time to first progress
    max_hold_sec: Optional[float] = None  # Max hold time before stale exit
    mfe_min_bps: Optional[float] = None  # Min favorable excursion expected quickly
    # Exit signal fields (spot strategies)
    is_exit_signal: bool = False
    reduce_only: bool = False


# =============================================================================
# Pre-Trade Gating System Types
# =============================================================================


@dataclass(frozen=True)
class MarketSnapshot:
    """
    Frozen, immutable snapshot of market state for decision making.
    
    Every stage in the pipeline reads from this snapshot to ensure consistency.
    Created once per tick by SnapshotBuilderStage.
    
    Strategy Signal Architecture Fixes - Requirement 3.11:
    - Added flow_rotation (EWMA smoothed orderflow signal)
    - Added trend_bias (HTF trend signal)
    - rotation_factor retained for backward compatibility (deprecated)
    
    Distance Field Semantics:
    - distance_to_poc_bps: SIGNED distance. Positive = price above POC, negative = price below POC.
      Formula: (price - poc) / mid_price * 10000
    - distance_to_vah_bps: ABSOLUTE distance. Always >= 0.
      Formula: abs(price - vah) / mid_price * 10000
    - distance_to_val_bps: ABSOLUTE distance. Always >= 0.
      Formula: abs(price - val) / mid_price * 10000
    
    Slippage Semantics:
    - expected_fill_slippage_bps: ONE-WAY slippage (entry fill only).
      Includes half-spread + depth/freshness/volatility penalties.
      For round-trip costs, multiply by 2 or add entry + exit separately.
    """
    # Identity
    symbol: str
    exchange: str
    timestamp_ns: int
    snapshot_age_ms: float
    
    # Price
    mid_price: float
    bid: float
    ask: float
    spread_bps: float
    
    # Depth
    bid_depth_usd: float
    ask_depth_usd: float
    depth_imbalance: float  # -1 to +1
    
    # Orderflow (multi-timeframe)
    imb_1s: float
    imb_5s: float
    imb_30s: float
    orderflow_persistence_sec: float
    
    # Volatility
    rv_1s: float
    rv_10s: float
    rv_1m: float
    vol_shock: bool  # rv_1s > rv_10s * 3
    
    # Regime (numeric scores + string labels)
    vol_regime: str  # "low", "normal", "high", "extreme"
    vol_regime_score: float  # 0-1
    trend_direction: str  # "up", "down", "neutral"
    trend_strength: float  # 0-1
    
    # Volume profile
    poc_price: Optional[float]
    vah_price: Optional[float]
    val_price: Optional[float]
    position_in_value: str  # "above", "below", "inside"
    
    # Execution estimates
    expected_fill_slippage_bps: float
    typical_spread_bps: float  # Rolling average for comparison
    
    # Data quality
    data_quality_score: float  # 0-1
    ws_connected: bool
    
    # AMT distance and rotation fields (Requirements 5.1, 5.2)
    # These have defaults since they may not be available when AMT levels are missing
    # Field names include _bps suffix to indicate units (basis points)
    # SIGNED: positive = price above level, negative = price below level
    distance_to_poc_bps: float = 0.0  # SIGNED: (price - poc) / mid_price * 10000
    # ABSOLUTE: always >= 0, measures distance regardless of direction
    distance_to_vah_bps: float = 0.0  # ABSOLUTE: abs(price - vah) / mid_price * 10000
    distance_to_val_bps: float = 0.0  # ABSOLUTE: abs(price - val) / mid_price * 10000
    
    # Split rotation signals (Strategy Signal Architecture Fixes - Requirement 3.11)
    flow_rotation: float = 0.0     # EWMA smoothed orderflow signal [-5, +5]
    trend_bias: float = 0.0        # HTF trend signal [-1, +1]
    rotation_factor: float = 0.0   # DEPRECATED: Legacy combined signal (-15 to +15)
    
    # Backward compatibility properties for deprecated field names (Requirement 5.1, 5.2)
    @property
    def distance_to_poc(self) -> float:
        """DEPRECATED: Use distance_to_poc_bps instead."""
        _log_deprecation_warning("distance_to_poc", "distance_to_poc_bps")
        return self.distance_to_poc_bps
    
    @property
    def distance_to_vah(self) -> float:
        """DEPRECATED: Use distance_to_vah_bps instead."""
        _log_deprecation_warning("distance_to_vah", "distance_to_vah_bps")
        return self.distance_to_vah_bps
    
    @property
    def distance_to_val(self) -> float:
        """DEPRECATED: Use distance_to_val_bps instead."""
        _log_deprecation_warning("distance_to_val", "distance_to_val_bps")
        return self.distance_to_val_bps
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for telemetry (key stats only)."""
        return {
            "symbol": self.symbol,
            "timestamp_ns": self.timestamp_ns,
            "snapshot_age_ms": self.snapshot_age_ms,
            "mid_price": self.mid_price,
            "spread_bps": self.spread_bps,
            "imb_5s": self.imb_5s,
            "vol_shock": self.vol_shock,
            "vol_regime": self.vol_regime,
            "trend_direction": self.trend_direction,
            "trend_strength": self.trend_strength,
            "data_quality_score": self.data_quality_score,
            # AMT fields (Requirements 6.1, 6.2, 6.3, 6.4)
            "poc_price": self.poc_price,
            "vah_price": self.vah_price,
            "val_price": self.val_price,
            "position_in_value": self.position_in_value,
            "distance_to_poc_bps": self.distance_to_poc_bps,
            "distance_to_vah_bps": self.distance_to_vah_bps,
            "distance_to_val_bps": self.distance_to_val_bps,
            # Split rotation signals (Requirement 3.11)
            "flow_rotation": self.flow_rotation,
            "trend_bias": self.trend_bias,
            "rotation_factor": self.rotation_factor,
        }


@dataclass
class TradeCandidate:
    """
    Proposed trade generated by CandidateGenerationStage.
    
    Contains side, expected edge, and all info needed for post-candidate veto.
    """
    symbol: str
    side: str  # "long" or "short"
    strategy_id: str
    profile_id: str
    
    # Edge estimates
    expected_edge_bps: float
    confidence: float  # 0-1
    
    # Prices
    entry_price: float
    stop_loss: float
    take_profit: Optional[float]
    
    # Sizing hints
    max_position_usd: float
    
    # For telemetry
    generation_reason: str
    snapshot_timestamp_ns: int
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for telemetry."""
        return {
            "symbol": self.symbol,
            "side": self.side,
            "strategy_id": self.strategy_id,
            "profile_id": self.profile_id,
            "expected_edge_bps": self.expected_edge_bps,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "generation_reason": self.generation_reason,
        }


@dataclass
class GateDecision:
    """
    Structured result from any gate stage.
    
    Provides detailed reasoning for pass/fail decisions for telemetry.
    """
    allowed: bool
    gate_name: str
    reasons: List[str] = field(default_factory=list)
    metrics: Dict[str, float] = field(default_factory=dict)
    timestamp_ns: int = field(default_factory=lambda: int(time.time() * 1e9))
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for telemetry."""
        return {
            "allowed": self.allowed,
            "gate_name": self.gate_name,
            "reasons": self.reasons,
            "metrics": self.metrics,
            "timestamp_ns": self.timestamp_ns,
        }


class ExitType(Enum):
    """
    Classification of exit reasons.
    
    SAFETY exits bypass min_hold time - they protect from catastrophic losses.
    INVALIDATION exits respect min_hold - they indicate strategy premise changed.
    """
    SAFETY = "safety"              # Hard stop, liquidation, data failure - ignores min_hold
    INVALIDATION = "invalidation"  # Orderflow flip, regime change - respects min_hold


@dataclass
class ExitDecision:
    """
    Structured exit decision with classification.
    
    Safety exits (hard stop, liquidation proximity, data failure) always allowed.
    Invalidation exits (orderflow flip, regime change) respect min_hold.
    """
    should_exit: bool
    exit_type: ExitType
    reason: str
    urgency: float  # 0-1, higher = more urgent
    confirmations: List[str] = field(default_factory=list)
    fee_check_result: Optional[Any] = None  # FeeAwareExitCheck when fee model is used
    fee_check_bypassed: bool = False
    fee_bypass_reason: Optional[str] = None
    
    def bypasses_min_hold(self) -> bool:
        """Safety exits ignore minimum hold time."""
        return self.exit_type == ExitType.SAFETY


# =============================================================================
# Symbol-Adaptive Parameters Types
# =============================================================================


@dataclass
class SymbolCharacteristics:
    """
    Rolling statistics for a symbol used for parameter adaptation.
    
    Tracks typical spread, depth, volatility, and daily range for each symbol.
    Used by AdaptiveParameterResolver to convert multiplier-based parameters
    to absolute values that are appropriate for each symbol's characteristics.
    
    Requirements: 1.1, 1.2, 1.3, 1.4
    """
    symbol: str
    
    # Spread characteristics (Requirement 1.1)
    typical_spread_bps: float  # EMA of recent spreads
    
    # Depth characteristics (Requirement 1.2)
    typical_depth_usd: float  # EMA of min(bid_depth, ask_depth)
    
    # Volatility characteristics (Requirements 1.3, 1.4)
    typical_daily_range_pct: float  # ATR / price, normalized to daily
    typical_atr: float  # Raw ATR value
    typical_volatility_regime: str  # Mode of recent regimes: "low", "normal", "high"
    
    # Metadata
    sample_count: int  # Number of samples collected
    last_updated_ns: int  # Timestamp of last update
    
    def is_warmed_up(self, min_samples: int = 100) -> bool:
        """
        Check if enough samples collected for reliable estimates.
        
        Args:
            min_samples: Minimum number of samples required (default 100)
            
        Returns:
            True if sample_count >= min_samples
        """
        return self.sample_count >= min_samples
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for serialization (e.g., Redis persistence).
        
        Returns:
            Dictionary with all fields as JSON-serializable values
        """
        return {
            "symbol": self.symbol,
            "typical_spread_bps": self.typical_spread_bps,
            "typical_depth_usd": self.typical_depth_usd,
            "typical_daily_range_pct": self.typical_daily_range_pct,
            "typical_atr": self.typical_atr,
            "typical_volatility_regime": self.typical_volatility_regime,
            "sample_count": self.sample_count,
            "last_updated_ns": self.last_updated_ns,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SymbolCharacteristics":
        """
        Create SymbolCharacteristics from dictionary.
        
        Args:
            data: Dictionary with all required fields
            
        Returns:
            SymbolCharacteristics instance
        """
        return cls(
            symbol=data["symbol"],
            typical_spread_bps=float(data["typical_spread_bps"]),
            typical_depth_usd=float(data["typical_depth_usd"]),
            typical_daily_range_pct=float(data["typical_daily_range_pct"]),
            typical_atr=float(data["typical_atr"]),
            typical_volatility_regime=str(data["typical_volatility_regime"]),
            sample_count=int(data["sample_count"]),
            last_updated_ns=int(data["last_updated_ns"]),
        )
    
    @classmethod
    def default(cls, symbol: str) -> "SymbolCharacteristics":
        """
        Create default characteristics for cold start.
        
        Used when no historical data is available for a symbol.
        Conservative defaults that work for most crypto assets.
        
        Args:
            symbol: The symbol identifier
            
        Returns:
            SymbolCharacteristics with conservative default values
        """
        return cls(
            symbol=symbol,
            typical_spread_bps=5.0,  # Conservative 5 bps
            typical_depth_usd=50000.0,  # $50k depth
            typical_daily_range_pct=0.03,  # 3% daily range
            typical_atr=0.0,  # Will be calculated
            typical_volatility_regime="normal",
            sample_count=0,
            last_updated_ns=0,
        )


# =============================================================================
# Candidate Generation Architecture Types (Requirement 4)
# =============================================================================


@dataclass
class CandidateSignal:
    """
    Intermediate signal representing a geometric setup before confirmation.
    
    This dataclass represents a trading opportunity detected by a strategy
    that has not yet been confirmed by flow/trend validation. It supports
    EITHER distance-based OR price-based SL/TP specification.
    
    Use normalize() to convert between formats.
    
    Requirement 4.1: CandidateSignal dataclass with required fields
    Requirement 4.2: Support EITHER distance-based OR price-based specification
    Requirement 4.3: Provide normalize() for conversion
    
    Attributes:
        symbol: Trading symbol (e.g., "BTCUSDT")
        side: Trade direction - "long" or "short"
        strategy_id: Identifier of the strategy that generated this candidate
        profile_id: Identifier of the trading profile
        entry_price: Proposed entry price
        sl_distance_bps: Stop loss distance in basis points (optional)
        tp_distance_bps: Take profit distance in basis points (optional)
        sl_price: Stop loss price (optional)
        tp_price: Take profit price (optional)
        setup_reason: Human-readable reason for the setup
        setup_score: Quality score for the setup (0-1, higher is better)
        requires_flow_reversal: Whether flow reversal is required for confirmation
        flow_direction_required: Required flow direction ("positive", "negative", or None)
        max_adverse_trend_bias: Maximum adverse trend bias allowed
        setup_timestamp_ns: Timestamp when setup was detected (nanoseconds)
    """
    symbol: str
    side: str  # "long" or "short"
    strategy_id: str
    profile_id: str
    entry_price: float
    
    # SL/TP - support EITHER distances OR prices (Requirement 4.2)
    sl_distance_bps: Optional[float] = None
    tp_distance_bps: Optional[float] = None
    sl_price: Optional[float] = None
    tp_price: Optional[float] = None
    
    # Setup metadata (Requirement 4.1)
    setup_reason: str = ""
    setup_score: float = 0.5  # 0-1 confidence in setup quality
    
    # Confirmation requirements (Requirement 4.11)
    requires_flow_reversal: bool = True
    flow_direction_required: Optional[str] = None  # "positive", "negative"
    max_adverse_trend_bias: float = 0.5
    
    # Dual threshold for EVGate (Requirement 2.11)
    # profitability_threshold_bps is passed to EVGate for economic viability check
    profitability_threshold_bps: Optional[float] = None
    
    # Timestamps
    setup_timestamp_ns: int = field(default_factory=lambda: int(time.time() * 1e9))
    
    def normalize(self, mid_price: float) -> "CandidateSignal":
        """
        Normalize to have both distance and price representations.
        
        If distances provided, calculates prices.
        If prices provided, calculates distances.
        Uses canonical formula: distance_bps = |price - entry| / mid_price * 10000
        
        Requirement 4.3: CandidateSignal SHALL provide normalize() that converts
        prices to distances or vice versa.
        
        Args:
            mid_price: Mid price for normalization (best_bid + best_ask) / 2
            
        Returns:
            New CandidateSignal with both distance and price fields populated
        """
        # Create a copy with updated values
        new_sl_distance_bps = self.sl_distance_bps
        new_tp_distance_bps = self.tp_distance_bps
        new_sl_price = self.sl_price
        new_tp_price = self.tp_price
        
        # Handle SL conversion
        if self.sl_distance_bps is not None and self.sl_price is None:
            # Convert distance to price
            if self.side == "long":
                new_sl_price = self.entry_price * (1 - self.sl_distance_bps / 10000)
            else:
                new_sl_price = self.entry_price * (1 + self.sl_distance_bps / 10000)
        elif self.sl_price is not None and self.sl_distance_bps is None:
            # Convert price to distance using canonical formula
            if mid_price > 0:
                new_sl_distance_bps = abs(self.entry_price - self.sl_price) / mid_price * 10000
            else:
                new_sl_distance_bps = 0.0
        
        # Handle TP conversion
        if self.tp_distance_bps is not None and self.tp_price is None:
            # Convert distance to price
            if self.side == "long":
                new_tp_price = self.entry_price * (1 + self.tp_distance_bps / 10000)
            else:
                new_tp_price = self.entry_price * (1 - self.tp_distance_bps / 10000)
        elif self.tp_price is not None and self.tp_distance_bps is None:
            # Convert price to distance using canonical formula
            if mid_price > 0:
                new_tp_distance_bps = abs(self.tp_price - self.entry_price) / mid_price * 10000
            else:
                new_tp_distance_bps = 0.0
        
        return CandidateSignal(
            symbol=self.symbol,
            side=self.side,
            strategy_id=self.strategy_id,
            profile_id=self.profile_id,
            entry_price=self.entry_price,
            sl_distance_bps=new_sl_distance_bps,
            tp_distance_bps=new_tp_distance_bps,
            sl_price=new_sl_price,
            tp_price=new_tp_price,
            setup_reason=self.setup_reason,
            setup_score=self.setup_score,
            requires_flow_reversal=self.requires_flow_reversal,
            flow_direction_required=self.flow_direction_required,
            max_adverse_trend_bias=self.max_adverse_trend_bias,
            profitability_threshold_bps=self.profitability_threshold_bps,
            setup_timestamp_ns=self.setup_timestamp_ns,
        )
    
    def to_strategy_signal(
        self,
        size: float,
        confirmation_reason: str,
    ) -> StrategySignal:
        """
        Convert to StrategySignal after confirmation.
        
        Requirement 4.7: Confirmation_Stage SHALL convert confirmed candidates
        to StrategySignal with SL/TP prices.
        
        Args:
            size: Position size for the trade
            confirmation_reason: Reason for confirmation (e.g., "flow=1.5,trend=0.2")
            
        Returns:
            StrategySignal ready for EVGate and execution
            
        Raises:
            ValueError: If sl_price or tp_price is not set (call normalize() first)
        """
        if self.sl_price is None:
            raise ValueError("sl_price must be set before converting to StrategySignal. Call normalize() first.")
        if self.tp_price is None:
            raise ValueError("tp_price must be set before converting to StrategySignal. Call normalize() first.")
        
        return StrategySignal(
            strategy_id=self.strategy_id,
            symbol=self.symbol,
            side=self.side,
            size=size,
            entry_price=self.entry_price,
            stop_loss=self.sl_price,
            take_profit=self.tp_price,
            meta_reason=f"{self.setup_reason}|{confirmation_reason}",
            profile_id=self.profile_id,
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for telemetry."""
        return {
            "symbol": self.symbol,
            "side": self.side,
            "strategy_id": self.strategy_id,
            "profile_id": self.profile_id,
            "entry_price": self.entry_price,
            "sl_distance_bps": self.sl_distance_bps,
            "tp_distance_bps": self.tp_distance_bps,
            "sl_price": self.sl_price,
            "tp_price": self.tp_price,
            "setup_reason": self.setup_reason,
            "setup_score": self.setup_score,
            "requires_flow_reversal": self.requires_flow_reversal,
            "flow_direction_required": self.flow_direction_required,
            "max_adverse_trend_bias": self.max_adverse_trend_bias,
            "setup_timestamp_ns": self.setup_timestamp_ns,
        }


class CandidateArbitrator:
    """
    Selects best candidate when multiple strategies emit for same symbol.
    
    Requirement 4.5: When multiple strategies emit candidates for the same symbol,
    the Candidate_Arbitrator SHALL select the best candidate based on:
    - setup_score (higher is better)
    - expected_ev (if available)
    - strategy_priority (configurable per strategy)
    
    Attributes:
        strategy_priorities: Dict mapping strategy_id to priority (higher is better)
    """
    
    def __init__(self, strategy_priorities: Optional[Dict[str, int]] = None):
        """
        Initialize the arbitrator.
        
        Args:
            strategy_priorities: Dict mapping strategy_id to priority.
                Higher priority values are preferred. Default priority is 0.
        """
        self.strategy_priorities = strategy_priorities or {}
    
    def select_best(
        self,
        candidates: List[CandidateSignal],
    ) -> Optional[CandidateSignal]:
        """
        Select best candidate based on setup_score and strategy priority.
        
        Requirement 4.5: Selection criteria:
        1. setup_score (higher is better) - primary criterion
        2. strategy_priority (higher is better) - tiebreaker
        
        Args:
            candidates: List of CandidateSignal objects to choose from
            
        Returns:
            Best CandidateSignal, or None if candidates list is empty
        """
        if not candidates:
            return None
        
        def score_candidate(c: CandidateSignal) -> tuple:
            """Score a candidate for comparison. Higher is better."""
            priority = self.strategy_priorities.get(c.strategy_id, 0)
            # Return tuple for comparison: (setup_score, priority)
            # Python compares tuples element by element
            return (c.setup_score, priority)
        
        return max(candidates, key=score_candidate)
    
    def set_priority(self, strategy_id: str, priority: int) -> None:
        """
        Set priority for a strategy.
        
        Args:
            strategy_id: Strategy identifier
            priority: Priority value (higher is better)
        """
        self.strategy_priorities[strategy_id] = priority
    
    def get_priority(self, strategy_id: str) -> int:
        """
        Get priority for a strategy.
        
        Args:
            strategy_id: Strategy identifier
            
        Returns:
            Priority value, or 0 if not set
        """
        return self.strategy_priorities.get(strategy_id, 0)