"""
CandidateGenerationStage - Generates TradeCandidate from strategy signals.

This stage wraps the existing signal + prediction logic and produces
a structured TradeCandidate object with side and expected edge.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional, Any

from quantgambit.signals.pipeline import Stage, StageContext, StageResult
from quantgambit.deeptrader_core.types import MarketSnapshot, TradeCandidate, GateDecision
from quantgambit.observability.logger import log_info, log_warning


@dataclass
class CandidateGenerationConfig:
    """Configuration for CandidateGenerationStage."""
    # Default max position size in USD
    default_max_position_usd: float = 10000.0
    # Minimum expected edge to even generate a candidate (pre-tradeability filter)
    min_expected_edge_bps: float = 0.0  # Set to 0 to let CandidateVeto handle it


class CandidateGenerationStage(Stage):
    """
    Generate TradeCandidate from strategy signals.
    
    This stage:
    1. Takes the signal from SignalStage (side, entry, SL, TP)
    2. Calculates expected edge based on strategy parameters
    3. Wraps everything into a TradeCandidate object
    
    The TradeCandidate is then passed to CandidateVetoStage for
    side-aware validation.
    """
    name = "candidate_generation"
    
    def __init__(
        self,
        strategy_registry: Any = None,
        config: Optional[CandidateGenerationConfig] = None,
    ):
        self.registry = strategy_registry
        self.config = config or CandidateGenerationConfig()
        self._trace_enabled = os.getenv("CANDIDATE_GEN_TRACE", "").lower() in {"1", "true"}
    
    async def run(self, ctx: StageContext) -> StageResult:
        # Get signal generated by earlier SignalStage
        signal = ctx.signal
        
        if not signal:
            # No signal was generated - this is expected, not an error
            ctx.rejection_reason = "no_signal"
            ctx.rejection_stage = self.name
            return StageResult.REJECT
        
        # Get snapshot for timestamp and price reference
        snapshot: Optional[MarketSnapshot] = ctx.data.get("snapshot")
        if not snapshot:
            ctx.rejection_reason = "no_snapshot_for_candidate"
            ctx.rejection_stage = self.name
            return StageResult.REJECT
        
        # Extract signal details (handle both dict and object)
        if isinstance(signal, dict):
            side = signal.get("side")
            entry_price = signal.get("entry_price") or snapshot.mid_price
            stop_loss = signal.get("stop_loss") or entry_price
            take_profit = signal.get("take_profit")
            strategy_id = signal.get("strategy_id") or "unknown"
            meta_reason = signal.get("meta_reason") or ""
            is_exit = signal.get("is_exit_signal", False) or signal.get("reduce_only", False)
        else:
            side = getattr(signal, "side", None)
            entry_price = getattr(signal, "entry_price", snapshot.mid_price)
            stop_loss = getattr(signal, "stop_loss", entry_price)
            take_profit = getattr(signal, "take_profit", None)
            strategy_id = getattr(signal, "strategy_id", "unknown")
            meta_reason = getattr(signal, "meta_reason", "")
            is_exit = getattr(signal, "is_exit_signal", False) or getattr(signal, "reduce_only", False)
        
        # Exit signals bypass candidate generation - pass through directly
        if is_exit:
            if self._trace_enabled:
                log_info(
                    "candidate_gen_exit_passthrough",
                    symbol=ctx.symbol,
                    side=side,
                )
            return StageResult.CONTINUE
        
        # Normalize side
        if side in {"buy", "long"}:
            side = "long"
        elif side in {"sell", "short"}:
            side = "short"
        else:
            ctx.rejection_reason = f"invalid_side:{side}"
            ctx.rejection_stage = self.name
            return StageResult.REJECT
        
        # Calculate expected edge in bps (prefer EVGate-derived net edge when available)
        ev_gate_result = ctx.data.get("ev_gate_result")
        expected_edge_bps = self._calculate_expected_edge(
            side=side,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            snapshot=snapshot,
            ev_gate_result=ev_gate_result,
        )
        
        # Calculate confidence based on prediction/signal quality and market conditions.
        # Prefer model prediction confidence when available so confidence telemetry
        # reflects current model certainty instead of static fallbacks.
        prediction = ctx.data.get("prediction") if isinstance(ctx.data, dict) else None
        confidence = self._calculate_confidence(signal, snapshot, prediction=prediction)
        
        # Get profile ID from context
        profile_id = ctx.profile_id or "unknown"
        
        # Get max position from risk limits or use default
        risk_limits = ctx.data.get("risk_limits") or {}
        max_position = risk_limits.get("max_position_usd") or self.config.default_max_position_usd
        
        # Apply size factor from global gate
        size_factor = ctx.data.get("size_factor", 1.0)
        max_position *= size_factor
        
        # Create TradeCandidate
        candidate = TradeCandidate(
            symbol=ctx.symbol,
            side=side,
            strategy_id=strategy_id,
            profile_id=profile_id,
            expected_edge_bps=expected_edge_bps,
            confidence=confidence,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            max_position_usd=max_position,
            generation_reason=meta_reason,
            snapshot_timestamp_ns=snapshot.timestamp_ns,
        )
        
        # Store candidate in context for downstream stages
        ctx.data["candidate"] = candidate
        
        # Store gate decision for telemetry
        ctx.data["gate_decisions"] = ctx.data.get("gate_decisions") or []
        ctx.data["gate_decisions"].append(GateDecision(
            allowed=True,
            gate_name=self.name,
            reasons=[],
            metrics={
                "expected_edge_bps": expected_edge_bps,
                "confidence": confidence,
                "side": side,
            },
        ))
        
        if self._trace_enabled:
            log_info(
                "candidate_generated",
                symbol=ctx.symbol,
                side=side,
                strategy_id=strategy_id,
                expected_edge_bps=round(expected_edge_bps, 2),
                confidence=round(confidence, 2),
            )
        
        return StageResult.CONTINUE
    
    def _calculate_expected_edge(
        self,
        side: str,
        entry_price: float,
        stop_loss: float,
        take_profit: Optional[float],
        snapshot: MarketSnapshot,
        ev_gate_result: Optional[Any] = None,
    ) -> float:
        """
        Calculate expected edge in basis points.
        
        Expected edge = potential profit - expected costs
        Costs include: spread (half), slippage, fees
        """
        if entry_price <= 0:
            return 0.0

        # Prefer EVGate-derived net edge to keep cost models consistent.
        if ev_gate_result is not None:
            try:
                g_bps = float(getattr(ev_gate_result, "G_bps", 0.0))
                total_cost_bps = getattr(ev_gate_result, "total_cost_bps", None)
                if total_cost_bps is not None:
                    net_edge = g_bps - float(total_cost_bps)
                    if self._trace_enabled:
                        log_info(
                            "candidate_edge_from_ev_gate",
                            side=side,
                            entry_price=round(entry_price, 6),
                            G_bps=round(g_bps, 2),
                            total_cost_bps=round(float(total_cost_bps), 2),
                            expected_edge_bps=round(net_edge, 2),
                        )
                    return net_edge
            except (TypeError, ValueError):
                pass
        
        # Calculate raw profit target
        if take_profit:
            if side == "long":
                profit_bps = (take_profit - entry_price) / entry_price * 10000
            else:
                profit_bps = (entry_price - take_profit) / entry_price * 10000
        else:
            # No TP set - estimate based on stop loss (assume 1.5:1 R:R)
            if side == "long":
                risk_bps = (entry_price - stop_loss) / entry_price * 10000
            else:
                risk_bps = (stop_loss - entry_price) / entry_price * 10000
            profit_bps = risk_bps * 1.5
        
        # Estimate costs
        # Half spread (we pay half when entering)
        spread_cost = snapshot.spread_bps / 2.0
        # Slippage estimate
        slippage_cost = snapshot.expected_fill_slippage_bps
        # Fee estimate (round trip: ~2-4 bps each way)
        fee_cost = 4.0  # Conservative estimate for taker fees
        
        total_cost = spread_cost + slippage_cost + fee_cost
        
        # Expected edge = profit - costs (doubled for round trip)
        expected_edge = profit_bps - (total_cost * 2)
        if self._trace_enabled:
            log_info(
                "candidate_edge_components",
                side=side,
                entry_price=round(entry_price, 6),
                stop_loss=round(stop_loss, 6) if stop_loss else None,
                take_profit=round(take_profit, 6) if take_profit else None,
                profit_bps=round(profit_bps, 2),
                spread_cost_bps=round(spread_cost, 2),
                slippage_cost_bps=round(slippage_cost, 2),
                fee_cost_bps=round(fee_cost, 2),
                total_cost_bps=round(total_cost, 2),
                expected_edge_bps=round(expected_edge, 2),
            )
        
        return expected_edge
    
    def _calculate_confidence(
        self,
        signal: Any,
        snapshot: MarketSnapshot,
        prediction: Optional[dict[str, Any]] = None,
    ) -> float:
        """Calculate confidence score for the trade candidate."""
        # Start with a neutral fallback. This is only used when neither the
        # prediction layer nor strategy signal provides confidence.
        confidence = 0.5

        # Prefer prediction confidence from the model/provider.
        pred_conf: Optional[float] = None
        if isinstance(prediction, dict):
            raw = prediction.get("confidence")
            try:
                if raw is not None:
                    pred_conf = float(raw)
            except (TypeError, ValueError):
                pred_conf = None
        if pred_conf is not None:
            confidence = pred_conf
        
        # Boost from signal confidence if available
        if isinstance(signal, dict):
            signal_conf = signal.get("confidence")
        else:
            signal_conf = getattr(signal, "confidence", None)
        
        if signal_conf is not None:
            try:
                signal_conf = float(signal_conf)
                # If both model and strategy confidence are available, keep
                # model confidence as primary and blend in strategy confidence.
                confidence = (0.7 * confidence) + (0.3 * signal_conf)
            except (TypeError, ValueError):
                pass
        
        # Adjust based on market conditions
        # Good data quality -> higher confidence
        confidence *= snapshot.data_quality_score
        
        # Narrow spread -> higher confidence
        if snapshot.spread_bps < 5:
            confidence *= 1.1
        elif snapshot.spread_bps > 10:
            confidence *= 0.9
        
        # Vol shock -> lower confidence
        if snapshot.vol_shock:
            confidence *= 0.7
        
        # Clamp to [0, 1]
        return max(0.0, min(1.0, confidence))
